### ISSUE TITLE
Check if already subscribed to channel

### ISSUE THREAD

**Issue by meister245** [slazarov/python-bittrex-websocket#15]
Hey,

I am writing an app that will send orders and using your library, will dynamically subscribe to the market ticker / orderbook. Right now every time I send an order, it calls a subscribe method for the given market.

But if I send multiple orders for the same market, I call the subscribe method multiple times. From the logs I see that you are handling it this like this:
"OrderBook subscription is already enabled for BTC-XRP. Ignoring..."

I was curious if there was a way to check if the given market orderbook / ticker is already subscribed to, so I don't make unnecesarry calls. :)

**Comment by slazarov** [comment]
Hi @meister245,
There is a private method in `get_sub_state` in `_auxiliary.py` which you can use:

```python
def get_sub_state(self, ticker, sub_type):
    """
    Check if the subscription for the specific ticker is in/active.

    :param ticker: Ticker name
    :type ticker: str
    :param sub_type: SUB_TYPE_ORDERBOOK; SUB_TYPE_ORDERBOOKUPDATE; SUB_TYPE_TRADES; SUB_TYPE_TICKERUPDATE
    :type sub_type: string
    :return: True(==SUB_STATE_ON) for Active; False(==SUB_STATE_OFF) for Inactive
    :rtype: bool
    """

    if ticker in self.list:
        return self.list[ticker][sub_type]['Active']
    else:
        return False
```

For example:
```python
from bittrex_websocket.constants import *
from bittrex_websocket.websocket_client import BittrexSocket

# Create the socket instance
ws = MySocket()
# Enable logging
ws.enable_log()
# Define ticker
ticker = ['BTC-ETH']
# Subscribe to live order book
ws.subscribe_to_orderbook(tickers)

sub_state = ws.tickers.get_sub_state(ticker, SUB_TYPE_ORDERBOOK)
# or
# if ws.tickers.get_sub_state(ticker, SUB_TYPE_ORDERBOOK) is SUB_STATE_ON:
#         >> don't subscribe
```

Since, I've only the basic information of what you are doing, I advise you to simply create a list with the tickers you have subscribed to and then query it instead of using private methods. It's more simple and elegant.

**Comment by meister245** [comment]
Hey @slazarov 

Thank you, this was exactly what I was looking for :)

**Comment by slazarov** [comment]
You are welcome, closing this issue until further notice.
