### ISSUE TITLE
Duplicate logging

### ISSUE THREAD

**Issue by meister245** [slazarov/python-bittrex-websocket#16]
Hey,

First of all, I'm not entirely sure if it is intended or it's because of my setup.
I have enabled logging and it's writing logs as intended, however I have observed the following.

If I subscribe to both ticker updates and orderbook, it will start logging duplicate rows.
I'm guessing that, for any time a subscribe method is called for the **first time**, it will start a duplicate logging.

I have tested this and I have found these results:
- only subscribing to ticker updates, no duplication
[only_tickers.log](https://github.com/slazarov/python-bittrex-websocket/files/1594341/only_tickers.log)
- only subscribing to orderbook updates, no duplication
[only_orderbook.log](https://github.com/slazarov/python-bittrex-websocket/files/1594340/only_orderbook.log)
- subscribing to ticker updates and orderbook, duplication
[both_orderbook_ticker.log](https://github.com/slazarov/python-bittrex-websocket/files/1594339/both_orderbook_ticker.log)

**Comment by slazarov** [comment]
Hey,

I don't get that issue. Post your execution code as per the [Guidelines](https://github.com/slazarov/python-bittrex-websocket/wiki/Creating-issues-guideline)

I used branch 0.0.6 with the following code to test:
```python
#!/usr/bin/python
# -*- coding: utf-8 -*-

from __future__ import print_function
from time import sleep
from bittrex_websocket.websocket_client import BittrexSocket

def main():
    class MySocket(BittrexSocket):
        def on_open(self):
            self.ticker_updates_container = {}

        def on_orderbook(self, msg):
            print('[OrderBook]: {}'.format(msg['MarketName']))

        def on_ticker_update(self, msg):
            name = msg['MarketName']
            if name not in self.ticker_updates_container:
                self.ticker_updates_container[name] = msg
                print('Just received ticker update for {}.'.format(name))

    # Create the socket instance
    ws = MySocket()
    # Enable logging
    ws.enable_log('test.log')
    # Define tickers
    tickers = ['BTC-ETH', 'BTC-NEO']
    # Subscribe to live order book
    ws.subscribe_to_orderbook(tickers)
    # Subscribe to ticker information
    ws.subscribe_to_ticker_update(tickers)

    while True:
        i = 0
        sync_states = ws.get_order_book_sync_state()
        for state in sync_states.values():
            if state == 3:
                i += 1
        if i == len(tickers):
            print('We are fully synced. Hooray!')
            for ticker in tickers:
                ob = ws.get_order_book(ticker)
                name = ob['MarketName']
                quantity = str(ob['Buys'][0]['Quantity'])
                price = str(ob['Buys'][0]['Rate'])
                print('Ticker: ' + name + ', Bids depth 0: ' + quantity + '@' + price)
            while len(ws.ticker_updates_container) < len(tickers):
                sleep(1)
            else:
                print('We have received updates for all tickers. Closing...')
                ws.disconnect()
            break
        else:
            sleep(1)

if __name__ == "__main__":
    main()
```

The test.log:
```
2017-12-30 14:32:56 - bittrex_websocket.websocket_client - INFO - [Connection][4a2ab10fab664f4a9ecf10a386e49577]: Trying to establish connection to Bittrex through https://socket-stage.bittrex.com/signalr.
2017-12-30 14:33:03 - bittrex_websocket.websocket_client - INFO - [Connection][4a2ab10fab664f4a9ecf10a386e49577]: Connection to Bittrex established successfully through https://socket-stage.bittrex.com/signalr.
2017-12-30 14:33:03 - bittrex_websocket._auxiliary - INFO - [Subscription][OrderBook][BTC-ETH]: Enabled.
2017-12-30 14:33:03 - bittrex_websocket._auxiliary - INFO - [Subscription][OrderBook][BTC-NEO]: Enabled.
2017-12-30 14:33:03 - bittrex_websocket._auxiliary - INFO - [Subscription][OrderBook][BTC-ETH]: Order book depth set to 10.
2017-12-30 14:33:03 - bittrex_websocket._auxiliary - INFO - [Subscription][OrderBook][BTC-NEO]: Order book depth set to 10.
2017-12-30 14:33:09 - bittrex_websocket.websocket_client - INFO - [Subscription][OrderBook][BTC-ETH]: Order book snapshot requested.
2017-12-30 14:33:10 - bittrex_websocket.websocket_client - INFO - [Subscription][OrderBook][BTC-ETH]: Order book snapshot received.
2017-12-30 14:33:10 - bittrex_websocket.websocket_client - INFO - [Subscription][OrderBook][BTC-NEO]: Order book snapshot requested.
2017-12-30 14:33:11 - bittrex_websocket.websocket_client - INFO - [Subscription][OrderBook][BTC-NEO]: Order book snapshot received.
2017-12-30 14:33:12 - bittrex_websocket._auxiliary - INFO - [Subscription][TickerUpdate][BTC-ETH]: Enabled.
2017-12-30 14:33:12 - bittrex_websocket._auxiliary - INFO - [Subscription][TickerUpdate][BTC-NEO]: Enabled.

```

**Comment by meister245** [comment]
Hey, thanks for looking into it, I did some additional testing and I can confirm based on your testing, that this is normally not an issue.

I managed to solve this issue by putting a waiting time between calling the ticker subscription and orderbook subscription. I think this behavior only occurs if there isn't an active connection to the websocket already.

Normally it would check if there is an active connection before subscribing, but since there is no active connection, it will try to establish connection with both the orderbook and ticker update methods, and this will result in duplicate logging.

I am using the 0.0.5.1 release.
Here is the execution code:

```
class BittrexWebsocket(BittrexSocket):
    def __init__(self, db, session, lock):
        BittrexSocket.__init__(self)

        self.logger = get_logger(__name__, './logs/websocket.log')

    def get_subs(self):
        sub = {}

        for k, v in self.tickers.list.items():
            sub[k] = {"orderbook": v['OrderBook']['Active'], "ticker_update": v['TickerUpdate']['Active']}

        return sub

    def sub_channels(self, market, logger):

        if not self.tickers.get_sub_state(market, SUB_TYPE_TICKERUPDATE) is SUB_STATE_ON:
            logger.debug('websocket, subscribing to ticker: %s' % market)
            self.subscribe_to_ticker_update(market.split())

        import time
        time.sleep(60)

        if not self.tickers.get_sub_state(market, SUB_TYPE_ORDERBOOK) is SUB_STATE_ON:
            logger.debug('websocket, subscribing to orderbook: %s' % market)
            self.subscribe_to_orderbook(market.split())

```

**Comment by slazarov** [comment]
Hey, enabling the logger is done in the top level and, not on subscription level.
Try enabling it before any other subscriptions through this method (like in the example):
```python
 # Create the socket instance
    ws = MySocket()
    # Enable logging
    ws.enable_log('test.log')
```

Regarding the way you solved the issue, there was a race issue but I patched it just now. Specifically:
* Fixed a bug when subscribing to multiple subscription types at once resulted in opening unnecessary connections even though there is sufficient capacity in the existing [Commit 7fd21c](https://github.com/slazarov/python-bittrex-websocket/commit/7fd21cad87a8bd7c88070bab0fd5774b0324332e)

Two of the methods were converted into queue objects so it should be ok. Can you test it?
`pip install git+https://github.com/slazarov/python-bittrex-websocket.git@0.0.6`

**Comment by meister245** [comment]
I'm sorry for the trouble, I found the root cause, your code is working fine, the error was in my code.

I was calling the the ticker update and orderbook subscriptions simultaneously, so it started connecting twice, however the real reason it was logging duplicates is that, I placed the enable logs() method here.

```
def on_open(self):
        self.enable_log('./logs/websocket.log')
```

After moving the method here, there are no more duplicate logs:

```
def __init__(self):
        BittrexSocket.__init__(self)
        self.enable_log('./logs/websocket.log')
```

Sorry for the confusion, your code was ok all the time :)

**Comment by meister245** [comment]
Didn't see your reply, we came to the same conclusion :)
I'll begin testing with 0.0.6.

**Comment by slazarov** [comment]
I am glad it's working for you and no worries because you reported one potential bug and we fixed another :).

**Comment by meister245** [comment]
Tested my code with 0.0.6, it correctly handles the connection and won't be logging duplicates.
Well done :)
