### ISSUE TITLE
Connection timed out

### ISSUE THREAD

**Issue by franz101** [slazarov/python-bittrex-websocket#19]
I'm trying to save the data from the ticker but after half a day i get a timeout.
My guess is:
It's always reconnecting? Instead of just staying at on subscription?
I used the sample script provided in the examples and modified it to run constantly...

requests.exceptions.ConnectionError: HTTPSConnectionPool(host='socket-beta.bittrex.com', port=443): Max retries exceeded with url: /signal
r/negotiate?connectionData=%5B%7B%22name%22%3A+%22coreHub%22%7D%5D&clientProtocol=1.5 (Caused by NewConnectionError('<urllib3.connection.V
erifiedHTTPSConnection object at 0x7f4bf6434128>: Failed to establish a new connection: [Errno 110] Connection timed out',))

**Comment by slazarov** [comment]
Reconnection is going to be included in branch 0.0.6. For now it’s partially implemented, but as I said it’s on the road map. Add the library to your watch list for updates.

**Comment by davidfindlay** [comment]
I've tried to overcome this by doing this:

```
                # Check for last trade insert
                numrows = c.execute("SELECT ts FROM trades ORDER BY ts DESC LIMIT 1;")
                db.commit()

                if numrows > 0:
                    last_ts = c.fetchone()[0]

                    # Check if last timestamp is longer than 60 seconds ago
                    if isinstance(last_ts, str):
                        last = datetime.datetime.strptime(last_ts.split(".")[0], "%Y-%m-%dT%H:%M:%S")
                    else:
                        last = last_ts

                    print(last)

                    last_ago = (datetime.datetime.utcnow() - last).total_seconds()
                    print("last_ago = %i" % last_ago)

                    if last_ago > 60:

                        print("More than 60 seconds since last trade inserted")

                        # Restart
                        ws.disconnect()

                        time.sleep(20)

                        print("Retrying to subscribe...")
                        ws.subscribe_to_trades(tickers)
```

However, calling ws.disconnect() doesn't actually seem to shutdown the websocket the same way doing a Ctrl-c does. How would I fully shut down the websocket bit and restart it? I've based my code on the example trades logger. Thanks,

David

**Comment by slazarov** [comment]
Checking the last timestamp might be double edge knife since there actually might be a gap between whatever trades/info you are getting that is more than 60 seconds.

A quick and dirty method before I implement it is to reinstantiate the websocket instance and resubscribe. Using `disconnect` and then subscribe should not work because `disconnect` should kill the thread that the socket is running in.

**Comment by slazarov** [comment]
Hi, I went through your issue again. The problem is with the url `socket-beta.bittrex.com`, can you update to the experimental v0.0.6 branch.
