### ISSUE TITLE
Version 0.0.6.x topic

### ISSUE THREAD

**Issue by slazarov** [slazarov/python-bittrex-websocket#21]
I haven't been active for the past 2/3 weeks so leaving a note here to highlight how `reconnection` will be implemented in v0.0.6.

The experimental implementation will work in the following way: 
- a watchdog thread will monitor subscriptions and check if their respective connections are active.
- if the connection is inactive, the watchdog will send an unsubscribe method followed by subscribe method
- a connection is marked as inactive upon exception in `def _init_connection(self, conn_obj)`

This implementation works on the base that connections are established independently of subscriptions. When an exception is reached in `def _init_connection(self, conn_obj)`, the script will try to reconnect with the extra URL. If this fails, the thread that holds the connection will die. However, since the watchdog is in a separate thread, it will detect that the connection is inactive and will try to establish a new one and the whole thing begins again.

As always, I am open to recommendations.

**[Update] 22/Jan/18**
Due to changes in the how the code is organised as of 0.0.6.x you might get an error message when you declare a variable in `on_open` and then try to access it immediately. E.g:

> Traceback (most recent call last):
>   File "python-bittrex-websocket/bittrex_websocket/examples/ticker_updates.py", line 49, in <module>
> 2018-01-22 07:49:39 - bittrex_websocket.websocket_client - INFO - [Connection][da64c763df6e411c9663004a1baefec6]:Trying to establish connection to Bittrex through https://socket-stage.bittrex.com/signalr.
>     main()
>   File "python-bittrex-websocket/bittrex_websocket/examples/ticker_updates.py", line 41, in main
>     while len(ws.ticker_updates_container) < len(tickers):
> **AttributeError: 'MySocket' object has no attribute 'ticker_updates_container'**

Quick workaround before I fix it is to introduce some delay after subscribing but before your logic, e.g `time.sleep(5)`.

**[Update] 21/Jan/18**
_Version 0.0.6.2_
* Every 5400s (1hr30) the script will force reconnection.
* Every reconnection (including the above) will be done with a fresh cookie
* Upon reconnection the script will check if the connection has been running for more than 600s (10mins). If it has been running for less it will use the backup url.

The timeouts (5400 and 10) are not final and are subject to results.

**[Update] 14/Jan/18**
I've been experimenting for the past few days and I have found that Bittrex has an embedded auto-reconnection. Meaning that if the connection drops and is reconnected through the same session either through `cfscrape` or `requests`, the invokes persist at a server level and sync with the client. Thought I have to note that I haven't tried to unsubscribe an invoke and apply a different session to it.

Anyways 0.0.6 is getting closer and thanks for the wait!

Stan

**Comment by snwokenk** [comment]
Hi,

I keep getting the  WebSocketConnectionClosedException that makes it impossible to collect any reasonable  amount of trade data for analysis. 

Will this implementation solve it?

Or is there already something that can be done? on_error?

**Comment by slazarov** [comment]
Yes, it should send a reconnection signal.

**Comment by slazarov** [comment]
Info update.

**Comment by slazarov** [comment]
v0.0.6 pushed to master. Let the bug games begin :)

**Comment by zemen77** [comment]
Hi,
is there a way to check for active subscriptions?

really good job man!
ty

**Comment by giorgio130** [comment]
Hi, just to let you know, I am still seeing WebSocketConnectionClosedException with version 0.0.6.1.

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/gevent/greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/site-packages/signalr/_connection.py", line 53, in wrapped_listener
    listener()
  File "/usr/lib/python2.7/site-packages/signalr/transports/_ws_transport.py", line 42, in _receive
    for notification in self.ws:
  File "/usr/lib/python2.7/site-packages/websocket/_core.py", line 107, in __iter__
    yield self.recv()
  File "/usr/lib/python2.7/site-packages/websocket/_core.py", line 296, in recv
    opcode, data = self.recv_data()
  File "/usr/lib/python2.7/site-packages/websocket/_core.py", line 313, in recv_data
    opcode, frame = self.recv_data_frame(control_frame)
  File "/usr/lib/python2.7/site-packages/websocket/_core.py", line 326, in recv_data_frame
    frame = self.recv_frame()
  File "/usr/lib/python2.7/site-packages/websocket/_core.py", line 360, in recv_frame
    return self.frame_buffer.recv_frame()
  File "/usr/lib/python2.7/site-packages/websocket/_abnf.py", line 340, in recv_frame
    self.recv_header()
  File "/usr/lib/python2.7/site-packages/websocket/_abnf.py", line 288, in recv_header
    header = self.recv_strict(2)
  File "/usr/lib/python2.7/site-packages/websocket/_abnf.py", line 375, in recv_strict
    bytes_ = self.recv(min(16384, shortage))
  File "/usr/lib/python2.7/site-packages/websocket/_core.py", line 430, in _recv
    return recv(self.sock, bufsize)
  File "/usr/lib/python2.7/site-packages/websocket/_socket.py", line 94, in recv
    "Connection is already closed.")
WebSocketConnectionClosedException: Connection is already closed.
Fri Jan 19 16:21:23 2018 <Greenlet at 0x7f20e12a29b0: wrapped_listener> failed with WebSocketConnectionClosedException

**Comment by slazarov** [comment]
Can you be more specific? 

- Running time
- code snippet
- is this the whole log? From the log you have pasted I can't trace it to my library. There is an exception handler for  `WebSocketConnectionClosedException` in `_init_connection`, but it seems it's not coming from there.

**Comment by giorgio130** [comment]
Hi, thanks for the reply! Unfortunately I cannot reproduce the issue anymore, it looks like it might happen when bittrex takes longer than foreseen to answer requests. The log I attached was everything I could see in my shell. You can find the whole script that produced the error @ https://pastebin.com/P9Dvs6fW . Since it's tracking also some minor currency, maybe it is dropping the connection when there are no events for a certain amount of time?

**Comment by slazarov** [comment]
That could be but if it drops it will exit ‘conn.wait’ in ‘_init_connection’ and it will reconnect. I might reduce ‘conn.wait’ to two hours and force a new cookie. Pm if you get it again.

**Comment by giorgio130** [comment]
I am pretty sure that the problem appeared after at most 30 minutes, if not
less. Anyway yes I'll do that, thanks :)

2018-01-20 9:29 GMT+01:00 Stanislav Lazarov <notifications@github.com>:

**Comment by slazarov** [comment]
I will test the code on my laptop as well. Can you confirm that besides the connection drop, everything is working ok? The data is streaming just fine?

**Comment by slazarov** [comment]
Info update.

**Comment by slazarov** [comment]
Info update.

**Comment by davidfindlay** [comment]
I'm still finding that when monitoring multiple trades feeds that they'll drop out randomly and silently. They don't reconnect. I haven't had the whole thing crash since I added a reconnected if no trades at all are received, but individual trades subscriptions will drop out.

**Comment by slazarov** [comment]
Try installing the second branch, I am trying to isolate a cookie issue. Also setting a timeout period of no trade are received after N time is a quick solution, but actually there might be no trades happening. You should monitor ‘on_debug’, it constantly sends data if the connection is alive.
