### ISSUE TITLE
Investigating subscribing to user deltas as well

### ISSUE THREAD

**Issue by JohanRensink** [slazarov/python-bittrex-websocket#22]
I've been playing around with the possibility of creating a logged-in version of this where we'll also subscribe to 'SubscribeToUserDeltas'. Receiving order creations, executions and cancellations in (pseudo) real time. 

I haven't been able to do this yet, not even in a very simple version where I log in with my browser and copy the .AspNet.ApplicationCookie generated and add it to the 'negotiate' request. 

Does anyone have an idea what to investigate next? How does the signalr 'know' that it's allowed subscribe to my specific userdeltas?

Thanks in advance for any ideas,

JR
PS: I've also unsuccesfully tried the __cfduid cookie

**Comment by slazarov** [comment]
To do that we have to bypass the google Authenticator, don’t we?

**Comment by JohanRensink** [comment]
If the goal is a 'hands-free' version: yes, but it's possible (not breaking the security ofc, but using the original seed to generate otp's like the GA app does, (I think this does the whole thing automatically https://github.com/pyotp/pyotp))

But that's not the issue right now, first version would be using anything from a logged in browser window.

**Comment by slazarov** [comment]
@JohanRensink that certainly should be put on the road map and I would be more than willing to collaborate with you on that.

**Comment by JohanRensink** [comment]
Cool, I'll probably have time to start on this in a couple of weeks (end of this month or so), I'll let you know what I find and I'll report back here. If it's fairly straightforward I'll create a pullrequest when the time comes.

**Comment by slazarov** [comment]
Awesome looking forward to it.
