### ISSUE TITLE
waiting 5 seconds per every update?

### ISSUE THREAD

**Issue by mixtale** [slazarov/python-bittrex-websocket#24]
I want to get every ticker_update data but it always take some delays about 5 seconds.
below is that I tried basic example and printed in on_ticker_update(self, msg) def.

[BTC-XRP] 0.00013021 / 2018-01-15T11:38:46.023
[BTC-XRP] 0.00013021 / 2018-01-15T11:38:51.63
[BTC-XRP] 0.00013014 / 2018-01-15T11:38:56.003
[BTC-XRP] 0.00013014 / 2018-01-15T11:39:01.347
[BTC-XRP] 0.00013009 / 2018-01-15T11:39:06.673
[BTC-XRP] 0.00013017 / 2018-01-15T11:39:16.92
[BTC-XRP] 0.00013017 / 2018-01-15T11:39:21.76
[BTC-XRP] 0.00013021 / 2018-01-15T11:39:26.34
[BTC-XRP] 0.00013021 / 2018-01-15T11:39:31.697

is there a way to get real time ticker_update msg ?

**Comment by slazarov** [comment]
What exactly do you want to get? Because ticket update gives you general information and it is delayed.

**Comment by mixtale** [comment]
oh I'm sorry i miss understood on_trade and on_ticker method.
thanks for your answer.

**Comment by slazarov** [comment]
You are welcome. Closing.
