### ISSUE TITLE
Random exception

### ISSUE THREAD

**Issue by mejmo** [slazarov/python-bittrex-websocket#30]
I got today this exception - I am monitoring all pairs. I accept the fact, that the connection may fail randomly, as Bittrex websocket is not to reliable... but these pairs stopped to be monitored. The exception is probably not caught and the thread exits. Do you have some idea how to fix this? 

The workaround here that comes to my mind is to monitor all files if the last trade is not too old -> probably connection down. But then I have to restart other pairs as well as you are using `max_tickers_per_conn` for one connection and it is not possible to restart just one chunk.

Catching this exception would help me a lot.

```
2018-01-27 16:35:17 - bittrex_websocket._auxiliary - INFO - [Subscription][Trades][USDT-NXT]: Enabled.
2018-01-27 16:35:17 - bittrex_websocket._auxiliary - INFO - [Subscription][Trades][USDT-OMG]: Enabled.
2018-01-27 16:35:17 - bittrex_websocket._auxiliary - INFO - [Subscription][Trades][USDT-XMR]: Enabled.
2018-01-27 16:35:17 - bittrex_websocket._auxiliary - INFO - [Subscription][Trades][USDT-XRP]: Enabled.
2018-01-27 16:35:17 - bittrex_websocket._auxiliary - INFO - [Subscription][Trades][USDT-XVG]: Enabled.
2018-01-27 16:35:17 - bittrex_websocket._auxiliary - INFO - [Subscription][Trades][USDT-ZEC]: Enabled.
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\gevent\hub.py", line 866, in switch
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\gevent\greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "C:\Python27\lib\site-packages\signalr\_connection.py", line 53, in wrapped_listener
    listener()
  File "C:\Python27\lib\site-packages\signalr\transports\_ws_transport.py", line 42, in _receive
    for notification in self.ws:
  File "C:\Python27\lib\site-packages\websocket\_core.py", line 107, in __iter__
    switch(value)
  File "C:\Python27\lib\site-packages\gevent\greenlet.py", line 538, in run
    self._report_error(sys.exc_info())
  File "C:\Python27\lib\site-packages\gevent\greenlet.py", line 520, in _report_error
    yield self.recv()
  File "C:\Python27\lib\site-packages\websocket\_core.py", line 296, in recv
    self._exc_info = exc_info[0], exc_info[1], dump_traceback(exc_info[2])
    opcode, data = self.recv_data()
  File "C:\Python27\lib\site-packages\websocket\_core.py", line 313, in recv_data
  File "C:\Python27\lib\site-packages\gevent\_tblib.py", line 370, in g
    opcode, frame = self.recv_data_frame(control_frame)
  File "C:\Python27\lib\site-packages\websocket\_core.py", line 326, in recv_data_frame
    frame = self.recv_frame()
  File "C:\Python27\lib\site-packages\websocket\_core.py", line 360, in recv_frame
    return self.frame_buffer.recv_frame()
  File "C:\Python27\lib\site-packages\websocket\_abnf.py", line 340, in recv_frame
    self.recv_header()
  File "C:\Python27\lib\site-packages\websocket\_abnf.py", line 288, in recv_header
    header = self.recv_strict(2)
  File "C:\Python27\lib\site-packages\websocket\_abnf.py", line 375, in recv_strict
    return f(a)
  File "C:\Python27\lib\site-packages\gevent\_tblib.py", line 425, in dump_traceback
    bytes_ = self.recv(min(16384, shortage))
  File "C:\Python27\lib\site-packages\websocket\_core.py", line 430, in _recv
    return dumps(tb)
TypeError: 'NoneType' object is not callable
Sat Jan 27 16:39:01 2018    return recv(self.sock, bufsize)
   File "C:\Python27\lib\site-packages\websocket\_socket.py", line 94, in recv
<built-in method switch of Greenlet object at 0x0000000008F23DF0> failed with TypeError

    "Connection is already closed.")
WebSocketConnectionClosedException: Connection is already closed.
Sat Jan 27 16:39:01 2018 <Greenlet at 0x90300e0L: wrapped_listener> failed with WebSocketConnectionClosedException
```

**Comment by slazarov** [comment]
Hey, I am trying to trace it but so far can’t find where to put the exception. WebsocketConnectionClosed is already handled within _init_create_connection so not from there. Another quick fix is to invoke a subscription after N seconds  for a specific ticker. I am thinking of a solution, thanks for patience!

**Comment by mejmo** [comment]
I heard from other developers, that it is kind of normal, that bittrex closes the connection if you are subscribed to all pairs. If there was a way to restart that particular connection it would be fine. I would just set lower `max_tickers_per_conn` which could help to better isolate the connection drop.

**Comment by slazarov** [comment]
If we are able to isolate that exception, the connection will auto restart, there is a mechanism.

**Comment by slazarov** [comment]
@mejmo please do a
`pip install git+https://github.com/slazarov/python-bittrex-websocket.git@0.0.6.2.1`
I've put some exception on the private _on channels. Lets see if we can intercept them.

**Comment by slazarov** [comment]
@mejmo can you also post the subscription part of your code?

**Comment by slazarov** [comment]
Fourth notification, please try running the code with Python3.6+. The main reason is that gevent which is a major component of the socket is dropping Python2.X support. Quote from their website:

> Due to security concerns, official support for Python 2.7.8 and earlier (without a modern SSL implementation) has been dropped. These versions are no longer tested with gevent, but gevent can still be installed on them. Supporting code will be removed in the next major version of gevent. 

+link: http://www.gevent.org/changelog.html#a1-2018-01-27

**Comment by Yidna** [comment]
I got a similar error and "fixed" it by catching it in signal_r/_connection.py (forcing the connection to close whenever the error is thrown). 
```
def wrapped_listener():
    try:
        listener()
    except:
        # print("@@@@@@\n@@@@@@\n@@@@@@\n@@@@@@\n@@@@@@")
        self.close()
    gevent.sleep()
```

@slazarov  Regarding reconnection, I noticed that the logs say that it is trying to re-establish the connection to Bittrex (and then logging that the connection was established correctly) whenever the connection drops. However, any log output from requesting order book snapshots are not shown. Is it not resubscribing to the order books? Was a new BittrexSocket created and I have to attach to that? (But enable_log() is a static method so it should continue to log) How do you handle reconnection?

**Comment by slazarov** [comment]
Reconnection is handled in _init_connection. It has worked in the scenarios I have tested but as you know there is one more extra scenario you haven’t tested :). 

If you could show your code + log, so we could replicate would be awesome. 

I haven’t tried editing the signalr client itself as I prefer to handle it within the socket itself but I can’t seem to find the exception because it’s not coming from init_connection.

The latest version is the one in the change log.

**Comment by Yidna** [comment]
It's difficult to replicate the error as it's not an exact moment in time - I just know that it's thrown when you overload the server and Bittrex kicks you off. I tried stressing the socket again and it didn't seem like all the connections restarted properly.

At the highest level, the exception should be thrown at the `wrapped_listener` function, which is defined in `start` and passed on to `__greenlet` as `gevent.spawn(wrapped_listener)` (inside of _connection.py of signalr).

I think it's likely that you'll be able to catch the error in one of the threads that handle the receiving of data from the socket. Which of your functions checks the socket for data and/or uses signalr->greenlet->gevent?

I dug around your code for a really long time but the thing that threw me off the most was that the stack trace doesn't lead to your code, which led me to dig around your dependencies (signalr), which led me to believe that the error occurs in a thread that was created but left alone (especially since receiving the error doesn't kill the main thread). So hopefully, if we can find out which thread the error came from, we can catch it and restart the thread?

**Comment by slazarov** [comment]
Hi, the threads run in the private _on channels. In the previous update I put some simple text exceptions in them to see if we can catch them. Can you confirm your version has them? Can’t give you the exact reference because I’m on the phone.
  

  
  

  
  
>

**Comment by slazarov** [comment]
Hi, I will try to post back today with info + additional info on how the code logic works. 

Also, I will do what I’ve mentioned in the issue below so people can start testing.
Best!

https://github.com/slazarov/python-bittrex-websocket/issues/35

**Comment by slazarov** [comment]
Too many issues for the same problem. Closing this one. All errors related to this issue will be discussed here:
https://github.com/slazarov/python-bittrex-websocket/issues/35
