### ISSUE TITLE
RuntimeWarning: Monkey-patching ssl after ssl has already been imported may lead to errors, including RecursionError on Python 3.6. Please monkey-patch earlier.   _warnings)

### ISSUE THREAD

**Issue by kylejan** [slazarov/python-bittrex-websocket#31]
version 0.0.6.2.2

it will show this warning:
RuntimeWarning: Monkey-patching ssl after ssl has already been imported may lead to errors, including RecursionError on Python 3.6. Please monkey-patch earlier.
  _warnings)

**Comment by slazarov** [comment]
1. Does it show in the examples?
2. Post your snippet + include imports. The socket should be imported at the top.
3. Does it work anyways?

**Comment by kylejan** [comment]
oh, it works when i put the bittrex_socket module import operation on the top of the code. thanks a lot!

**Comment by slazarov** [comment]
Great!
