### ISSUE TITLE
Websocket failing to connect

### ISSUE THREAD

**Issue by vegapit** [slazarov/python-bittrex-websocket#32]
Good Morning,

The websocket connection has recently been failing in my script. Is it due to upgrades on the server side or I need to upgrade one of the modules I am using.

Here is the list of the modules in my pip3:

asn1crypto (0.22.0)
bittrex-websocket (0.0.6.2.2)
certifi (2017.4.17)
cffi (1.11.4)
cfscrape (1.9.2)
chardet (3.0.4)
command-not-found (0.3)
cryptography (2.1.4)
distro-info (0.17)
Events (0.3)
gevent (1.3a1)
greenlet (0.4.12)
httplib2 (0.9.2)
idna (2.5)
keyring (10.4.0)
keyrings.alt (2.2)
language-selector (0.1)
numpy (1.14.0)
pip (9.0.1)
pycparser (2.18)
pycrypto (2.6.1)
PyExecJS (1.5.1)
pygobject (3.24.1)
pyOpenSSL (17.5.0)
python-apt (1.4.0b3)
python-bittrex (0.3.0)
python-debian (0.1.30)
pyxdg (0.25)
PyYAML (3.12)
requests (2.7.0)
SecretStorage (2.3.1)
setuptools (36.2.7)
signalr-client (0.0.7)
six (1.10.0)
sseclient (0.0.18)
ssh-import-id (5.7)
systemd-python (234)
ufw (0.35)
unattended-upgrades (0.1)
urllib3 (1.21.1)
websocket-client (0.46.0)
wheel (0.29.0)

Cheers

**Comment by slazarov** [comment]
Morning, post code + log.

**Comment by slazarov** [comment]
Have you installed node.js?

**Comment by vegapit** [comment]
The two machines I tested it on do not have node.js installed. Should I try to install it?

**Comment by vegapit** [comment]
That was it! Apologies for the inconvenience. I must have moved the script from one server to another and did not realise the node.js dependency.

Cheers

**Comment by slazarov** [comment]
Awesome and good luck :)
