### ISSUE TITLE
ImportError: No module named 'bittrex_websocket'

### ISSUE THREAD

**Issue by coderootme** [slazarov/python-bittrex-websocket#5]
So I installed everything with:

```
sudo apt-get install python-setuptools python-dev build-essential libssl-dev libffi-dev
sudo easy_install pip
pip install git+https://github.com/slazarov/python-bittrex-websocket.git
```

Then when I try to execute:

`python /usr/local/lib/python2.7/dist-packages/bittrex_websocket/examples/ticker_updates.py`

I get the following error:

```
Traceback (most recent call last):
  File "ticker_updates.py", line 18, in <module>
    from bittrex_websocket.websocket_client import BittrexSocket
ImportError: No module named bittrex_websocket.websocket_client
```

What did I miss?

**Comment by slazarov** [comment]
My best guess is that **(1)** you installed `easy_install` with `sudo` and messed the permissions. I am no linux expert so I found the following two solutions googling, try them:
`sudo chmod -R o+rwx /usr/local/lib/python2.7/dist-packages/` 
or
`sudo chmod -R ugo+rX /usr/local/lib/python2.7/dist-packages/`

**(2)** Another thing that might be causing it could be that you have python 2 and 3, and mismatched pip.

**(3)** Try setting up a virtualenv and test it:
```
pip install virtualenv
cd ~
virtualenv socket_test
source socket_test/bin/activate
pip install bittrex_websocket 
# I did this on python3 so my path to the file looked like this
python socket/lib/python3.6/site-packages/bittrex_websocket/examples/ticker_updates.py
```
For references: http://docs.python-guide.org/en/latest/dev/virtualenvs/

**(4)** Try the docker image as well.

I could install a fresh copy of ubuntu and give it a try but as I said my best guess is **(1)** and I would like you to try the above solutions first.
