### ISSUE TITLE
Incomplete?

### ISSUE THREAD

**Issue by Serpens66** [slazarov/python-bittrex-websocket#54]
Hi :)

Why do all the interesting functions have "raise NotImplementedError" ?
So in fact this project is not functional yet? Or where can I find "subscribe_to_orderbook" and other functions?

In addition:
I struggle with this "conn.wait()" command... It seems this is blocking, but without it nothing works.
So how can I start the WS connection and still continue the script simultanously?

**Comment by slazarov** [comment]
Hi, please familiarize yourself with abstract methods if you are concerned with NotImplementedError and read the readme on how to start the socket.
