### ISSUE TITLE
Is there a version with a working subscribe_to_orderbook()

### ISSUE THREAD

**Issue by Crimees** [slazarov/python-bittrex-websocket#65]
First of all thanks for this amazing contribution

Subscribe_to_orderbook() seems to have disappeared in the latest version. Does this have to do with the BITTREX API change? Is the old one still working and do you have a commit ID I can downgrade to for that one ?

Thank you !

**Comment by slazarov** [comment]
Hi, thanks for the kind words. The subscribe to order book is available for versions lower than v1. The removal is partly due to the change in the api. You can download it from the releases section but I don’t provide any support for it. I am developing an alternative right now but there is no eta.
  

  
  

  
  
>

**Comment by lucasgadams** [comment]
+1 on this. Anyway I can help implementing the subscribe_to_orderbook function? What makes it difficult to port the old code to the new api?

**Comment by slazarov** [comment]
It’s an open source project so anyone can help, I have always encouraged it. The only difficulty is the lack of personal time on my behalf :).

**Comment by slazarov** [comment]
As promised, the function is implemented again. Check the example for more info:
https://github.com/slazarov/python-bittrex-websocket/blob/master/examples/order_book.py

**Comment by volkovartem77** [comment]
Hi guys, you can use this code: https://github.com/volkovartem77/bittrex_orderbook
It's Bittrex websocket order book in Python
