### ISSUE TITLE
Unsubscribe from specific event without disconnection other events

### ISSUE THREAD

**Issue by KNizaev** [slazarov/python-bittrex-websocket#66]
Hello, is it possible to dynamically unsubsribe from one specific event?

Something like:
```
class UnsubscribeEvent(Event):
    """
    Handles the event of unsubscribing specific ticker(s) from specific channels.
    """
    def __init__(self, invoke, *payload):
        self.type = EventTypes.UNSUBSCRIBE
        self.invoke = invoke
        self.payload = payload
```
but i don`t understand is it possible in SignalR?

**Comment by slazarov** [comment]
Bittrex hasn’t released any unsubscribing methods. Also   QueryExchangeState is an one off invoke, you don’t subscribe to anything.
  

  
  

  
  
>

**Comment by KNizaev** [comment]
Thanks for your work!
