### ISSUE TITLE
Authentication and trade executions

### ISSUE THREAD

**Issue by JSterling8** [slazarov/python-bittrex-websocket#76]
Is there currently a way to authenticate and receive executions? I've tried the .authenticate() method, but it doesn't seem to work. In fact, I can no longer get order books if I authenticate. Is this something broken? An example would be really helpful, if one is available?

**Comment by slazarov** [comment]
Works on my end for all private channels, i.e there is an output upon placing/cancelling order. I haven't tested filling an order but there shouldn't be any difference. This is the example code I am using:

```python
from time import sleep
from bittrex_websocket import BittrexSocket, BittrexMethods

def main():
    class MySocket(BittrexSocket):
        def on_public(self, msg):
            print(msg)

        def on_private(self, msg):
            # THE OUTPUT WILL COME FROM HERE
            print(msg)

    # Create the socket instance
    ws = MySocket()
    # Enable logging
    ws.enable_log()
    ws.authenticate('API_KEY', 'API_SECRET')
    while True:
        sleep(1)

if __name__ == "__main__":
    main()
```

Have you checked the docs https://python-bittrex-websocket-docs.readthedocs.io/en/latest/methods.html?

**Comment by JSterling8** [comment]
Thanks for the code snippet. Yeah, read the docs. I think my issue came from trying to combine an OrderBook and private web socket class. I've split it out into two classes now OrderBookSocket and ExecutionsSocket and it works as expected. Thanks for the help.
