### ISSUE TITLE
authenticate callback exception

### ISSUE THREAD

**Issue by hippokylejan** [slazarov/python-bittrex-websocket#77]
after calling authenticate, it will throw index error when dealing with AUTHENTICATE callback, because you do not append invoke type to self.invoke when send AUTHENTICATE event

**Comment by slazarov** [comment]
AUTHENTICATE is called from GET_AUTH_CONTENT that’s why it is not recorded. What version number are you using? Post your snippet and logs.

**Comment by hippokylejan** [comment]
the response of authenticate will have 'R' in kwargs whose value is not bool, then it will throw exception in __is_query_invoke function, you have to deal with this. the easiest way is to add invoke corresponding to AUTHENTICATE request

**Comment by hippokylejan** [comment]
besides, after i call authenticate, i cannot receive private message

**Comment by slazarov** [comment]
Hi, from the short log you have posted I can see that `BittrexMethods.GET_AUTH_CONTENT` has been authenticated, meaning that all private messages will be send to the private channels as per the code's logic:

```python
hub.client.on(BittrexParameters.BALANCE_DELTA, self._on_private)
hub.client.on(BittrexParameters.ORDER_DELTA, self._on_private)
```

Furthermore `BittrexMethods.AUTHENTICATE` is not requested from `_is_query_invoke`, it's invoked from it. Only `BittrexMethods.GET_AUTH_CONTENT` passes through it and as I mentioned above, as evident by your log, it has passed successfully.

Anyways, after placing an order I get an output in the following template in `def on_private(self, msg):`

```
{
    AccountUuid : Guid,
    Nonce       : int,
    Type        : int,
    Order: 
    {
        Uuid              : guid,
        Id                : long,
        OrderUuid         : guid,
        Exchange          : string,
        OrderType         : string,
        Quantity          : decimal,
        QuantityRemaining : decimal,
        Limit             : decimal,
        CommissionPaid    : decimal,
        Price             : decimal,
        PricePerUnit      : decimal,
        Opened            : date,
        Closed            : date,
        IsOpen            : bool,
        CancelInitiated   : bool,
        ImmediateOrCancel : bool,
        IsConditional     : bool,
        Condition         : string,
        ConditionTarget   : decimal,
        Updated           : date
    }
}
```

Furthermore, the time gap between the messages is 2 seconds apart which leads me to think that you are making additional subscriptions. Are you using `ws.subscribe_to_orderbook` as well? If yes, then this is another story and you have to specify that.

I am unable to replicate your exception, unless you paste your code snippet + mention any modifications you have made.

**Comment by hippokylejan** [comment]
oh i see, is that the balance delta only be received after balance changed?

**Comment by slazarov** [comment]
Correct, if you want to request a balance snapshot you have to do it through the REST API.

Are you making additional calls?

**P.s:** the callback is called BALANCE_DELTA for a reason, i.e BALANCE_CHANGES.

**Comment by hippokylejan** [comment]
i see, thanks a lot!

**Comment by KevinTurnbull** [comment]
I'm not sure I understand how the solution was found here. I am having the same issue as this.

I've called authenticate with my key and secret; if I don't use authenticate (i.e. don't register for information about orders) then I don't get this crash. It also only sometimes crashes like this since it's only an infrequent crash. Thoughts?

```
  File "/code/market/sockets.py", line 61, in _connection_handler
    self.connection.conn.start()
  File "/usr/local/lib/python3.6/dist-packages/bittrex_websocket/_signalr.py", line 53, in start
    self.queue_handler()
  File "/usr/local/lib/python3.6/dist-packages/bittrex_websocket/_signalr.py", line 64, in queue_handler
    raise self.exception
  File "/usr/local/lib/python3.6/dist-packages/bittrex_websocket/_signalr.py", line 41, in wrapped_listener
    listener()
  File "/usr/local/lib/python3.6/dist-packages/signalr/transports/_ws_transport.py", line 42, in _receive
    self._handle_notification(notification)
  File "/usr/local/lib/python3.6/dist-packages/bittrex_websocket/_signalr.py", line 105, in _handle_notification
    self._connection.received.fire(**data)
  File "/usr/local/lib/python3.6/dist-packages/signalr/events/_events.py", line 15, in fire
    handler(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/bittrex_websocket/websocket_client.py", line 298, in _on_debug
    self._is_query_invoke(kwargs)
  File "/usr/local/lib/python3.6/dist-packages/bittrex_websocket/websocket_client.py", line 302, in _is_query_invoke
    invoke = self.invokes[int(kwargs['I'])]['invoke']
IndexError: list index out of range

list index out of range
```
