### ISSUE TITLE
Error messages not being thrown

### ISSUE THREAD

**Issue by wixihatchi** [slazarov/python-bittrex-websocket#85]
If I have an error in my code within the BittrexSocket class, it will not throw an error.  Even if it's a syntax error, it just shuts down the thread as if it ended natrually, but it doesn't display the error.

**Comment by slazarov** [comment]
Which methods have you overridden?
Perhaps you are missing try/except in your code?

**Comment by wixihatchi** [comment]
It looks like i just need to call enable_log() to show the errors.  

It seems that few errors trigger the on_error() function.  What types of errors is this for?

**Comment by slazarov** [comment]
Related to wrong signalr invoking, what errors are you getting?

**Comment by wixihatchi** [comment]
The only errors I get through on_error() is for disconnections.

[2019-01-30 08:23:36,125][ERROR] Exception = <class 'websocket._exceptions.WebSocketConnectionClosedException'>, Message = <Connection is already closed.>.

[2019-01-29 06:56:18,279][ERROR] Connection timeout after 10 seconds. Sending a reconnection signal.
[2019-01-29 06:57:48,579][ERROR] 
Unhandled Exception = <class 'requests.exceptions.HTTPError'>, Message = <524 Server Error: Origin Time-out for url: https://socket.bittrex.com/signalr/negotiate?connectionData=%5B%7B%22name%22%3A+%22c2%22%7D%5D&clientProtocol=1.5>.
Auto-reconnection is disabled for unhandled exceptions.
Report to https://github.com/slazarov/python-bittrex-websocket.

These aren't a problem though.  I think I have fixed my problem by enabling log.  

It would be useful to have an on_close() that runs when auto-reconnection is disabled.  That way I could restart the connection manually.  Right now I am intercepting log messages to alert my app that the websocket is closed.  Having on_close() would just be cleaner with less code.
