### ISSUE TITLE
Unhandled Exception <[Errno 104] Connection reset by peer>

### ISSUE THREAD

**Issue by LiangpingLi** [slazarov/python-bittrex-websocket#86]
I saw this error randomly, it can't handled by auto reconnection. Do you have some ideas how to fix this?

ERROR: [2019-01-17 10:33:14,569][websocket_client.py:169][20797:SocketConnectionThread]
Unhandled Exception = <class '_socket.error'>, Message = <[Errno 104] Connection reset by peer>.
Auto-reconnection is disabled for unhandled exceptions.
Report to https://github.com/slazarov/python-bittrex-websocket.

**Comment by slazarov** [comment]
The exception should be added to def _connection_handler in websocket_client.py. By default new exceptions are not auto reconnected until the reason for their occurrence is found.

Unhandled Exception = <class '_socket.error'>, Message = <[Errno 104] Connection reset by peer>.

**Comment by LiangpingLi** [comment]
I see, thanks a lot!
